pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				echo 'Checking out...'
				git branch: 'master', url: 'https://github.com/Solange-o/devops-23-24-JPE-1212208.git'
				}
			}
		stage('Assemble') {
			steps {
				echo 'Building...'
				dir('CA2/Part1') {
				sh 'chmod +x ./gradlew'
				sh './gradlew assemble'
				}
                            }
			}
		stage('Test') {
			steps {
				echo 'Building...'
				dir('CA2/Part1'){
				sh './gradlew test'
				junit '**/build/test-results/test/*.xml'
				}
                            }
			}
		stage('Archive') {
			steps {
				echo 'Archiving...'
				dir('CA2/Part1'){
				archiveArtifacts 'build/libs/*.jar'
			}
		    }
		}
	}
}