pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				echo 'Checking out...'
				git 'https://bitbucket.org/pssmatos/gradle_basic_demo'
				}
			}
		stage('Build') {
			steps {
				echo 'Building...'
				sh './gradlew clean build'
				}
			}
		stage('Archiving') {
			steps {
				echo 'Archiving...'
				archiveArtifacts 'build/distributions/*'
			}
		}
	}
}