pipeline {
	agent any
	stages {
		stage('Checkout') {
			steps {
				echo 'Checking out...'
				git 'https://github.com/Solange-o/devops-23-24-JPE-1212208/tree/master/CA2'
				}
			}
		stage('Assemble') {
			steps {
				echo 'Building...'
				sh './gradlew build'
				}
			}
		stage('Build') {
			steps {
				echo 'Building...'
				sh './gradlew bootrun'
				}
			}
		stage('Archiving') {
			steps {
				echo 'Archiving...'
				archiveArtifacts 'build/distributions/*'
			}
		}
	}
}